# Generated by Django 5.2.5 on 2025-08-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='total_seats',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
